// GLUP — nivel 3.
'use strict';
(() => {
  const { screen, join } = NIVEL;
  // ---------------------------------------------------------------- 3 · El bosque de raíces
  // Al atardecer, bajo los cipreses. Primera mitad por la copa con el aleteo (el tronco de cinco, ramas
  // separadas por seis sobre un zarzal, el molinillo y su compuerta, la caja que se sorbe hacia arriba
  // desde debajo de la rama y la placa). Tía Lapa, pegada a su roca en el hueco, da la ventosa. Segunda
  // mitad en vertical: tres chimeneas de raíces cada vez más duras (la de aprendizaje; la de la raíz
  // pelada, que se salta con impulso y aleteo, con zarzas en el fondo; y la ancha con un mosquito dentro
  // y dos tramos pelados), y la copa otra vez hasta la barca.
  // Secretos: la percha del anzuelo sobre el molinillo (mordisco), la cueva tapiada al pie de la primera
  // masa (guindilla), la cámara bajo la piedra rajada de lo alto de la segunda (panzazo) y la cueva del
  // fuego fatuo a sus pies, con el charco al lado (chorro).
  // (Pantallas generadas a partir de rectángulos; cada fila son 20 celdas.)
  const raices = join(
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '...........*........',
      '..........===.......',
      '....................',
      '.@..N..,......f.."..',
      '####################',
      '####################',
      '####################'),
    screen(
      '....................',
      '....................',
      '....................',
      '..............*.....',
      '.............====...',
      '....................',
      '......######........',
      '..m...######........',
      '......######........',
      '......######........',
      '...?..######........',
      '##################^^',
      '####################',
      '####################'),
    screen(
      '....................',
      '....................',
      '..........*.........',
      '....................',
      '.............===....',
      '...====.............',
      '....................',
      '.........m..........',
      '....................',
      '....................',
      '...................V',
      '^^^^^^^^^^^^^^^^^###',
      '####################',
      '####################'),
    screen(
      '..............###...',
      '..............###...',
      '............*.###...',
      '...........==..G....',
      '.........O.....G....',
      '...............G....',
      '...............G....',
      '...............G....',
      '...............G....',
      '...............G....',
      '.......f.......G..*.',
      '####################',
      '####################',
      '####################'),
    screen(
      '................###.',
      '................###.',
      '................###.',
      '.................G..',
      '.................G..',
      '.................G..',
      '......c..........G..',
      '.....===.........G..',
      '.................G..',
      '.................G..',
      '.L.?........P....G..',
      '####################',
      '####################',
      '####################'),
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....L....Q....,..?..',
      '####################',
      '####################',
      '####################'),
    screen(
      '....................',
      'M......L............',
      'M...##############..',
      'M...M#############..',
      'M...M#############..',
      'M.*.M#############..',
      'M...M#############..',
      'M...M#############..',
      'M...M#############..',
      '....M#########...X..',
      '....M#########.*.X..',
      '####################',
      '####################',
      '####################'),
    screen(
      '....................',
      '.............L......',
      '.......M...####xx###',
      '.......M.*.M##....##',
      '.......M...M##...*##',
      '.......M...#########',
      '.......M...#########',
      '.......M...#########',
      '.......M...M########',
      '...........M#######.',
      'r..?.......M#######.',
      '#########^^#########',
      '####################',
      '####################'),
    screen(
      '....................',
      '....................',
      '####................',
      '####................',
      '####................',
      '####................',
      '####................',
      '####......m.....*...',
      '####...........===..',
      '...F................',
      '*..F..........f.....',
      '#######~~~~#########',
      '#######~~~~#########',
      '####################'),
    screen(
      '....................',
      '...M................',
      '...M....############',
      '...M....M###########',
      '...#....M###########',
      '...#.m..M###########',
      '...M....############',
      '...M....############',
      '...M..*.M###########',
      '........M###########',
      '.L?.....M###########',
      '####################',
      '####################',
      '####################'),
    screen(
      '....................',
      '..............*.....',
      '####................',
      '####.............===',
      '####.....===........',
      '####................',
      '####.........m......',
      '####................',
      '####................',
      '####................',
      '####................',
      '####^^^^^^^^^^^^^^^^',
      '####################',
      '####################'),
    screen(
      '....................',
      '....................',
      '....................',
      '....######..........',
      '....######..........',
      '....######..........',
      '....######..........',
      '....######..........',
      '....######..........',
      '....######..........',
      '....######......f...',
      '^^^^################',
      '####################',
      '####################'),
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '..L..N....H...,.....',
      '####################',
      '####################',
      '####################'),
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '........E...........',
      '######~~~~~~~~~~~~~~',
      '######~~~~~~~~~~~~~~',
      '####################'));
  NIVEL.registrar({ id: 'raices', name: 'El bosque de raíces', theme: 'dusk', ambiente: 'raices', music: 'marsh', par: 260, rows: raices,
    intro: 'Bajo los cipreses, las raíces trepan como muros.',
    ruca: ['Aquí las raíces crecen hacia arriba, como paredes, y la Garza anida más allá de ellas. Dicen que una lapa vieja, en el hueco del bosque, sabe cómo subirlas. Tú, de momento, por las ramas: ¡aletea!',
      'Ya casi estás. Esa agua lleva a la barca. Y si alguna vez vuelves con más trucos, mira bien los muros: a este bosque le sobran escondites.'],
    signs: [
      'Cinco de alto: salta y, en el aire, salta otra vez. Y sopla al mosquito antes de que te pique.',
      'Mantén {up} y {fish}: Bigotes sorbe hacia arriba, también lo que hay sobre una rama. La caja, a la placa.',
      'Arriba no hay más camino que las raíces. Agárrate, impúlsate y… no mires a las zarzas.',
      'Donde la raíz está pelada no hay quien se agarre: impúlsate de la otra pared y aletea hasta la raíz de arriba.',
      'Dentro de la chimenea ronda un mosquito. Un soplido lo aparta, también agarrada al muro.'],
    maestro: { quien: 'lapa', poder: 'ventosa',
      dialogo: ['¿Y tú qué miras? Nunca has visto una lapa, ¿eh? Pues aquí me tienes, pegada a mi roca desde antes de que nacieras.',
        '¿Subir las raíces? Hay que agarrarse. Como yo. Nadie se agarra como una lapa.',
        'Hmpf. Anda, toma una lapa del pantano. Que el pez aprenda a pegarse, que buena falta le hace.'],
      despedida: 'Empuja contra el muro de raíces y salta de pared en pared. Donde la raíz esté pelada, aletea. Y no me hagas repetirlo.' },
    secretos: [{ poder: 'mordisco', crias: 1 }, { poder: 'guindilla', crias: 1 }, { poder: 'panzazo', crias: 1 }, { poder: 'chorro', crias: 1 }] });
})();
