// GLUP — nivel 4 · El molino anegado.
// Tormenta. Se llega con soplido, aleteo y ventosa. Primera mitad: surcos anegados, la chimenea de raíces,
// la carrera del molinillo por el túnel del caz, la esclusa de la placa y Olga, que pide que le desatasques
// la compuerta del molino (encargo «dianas»: la diana está alta en la fachada, sobre el caz; hay que saltar y
// escupir la piedra en el aire). Olga da el trago de agua (chorro). Segunda mitad: apagar hogueras, flotar sobre el río, la cortina
// de fuego desde el nenúfar, el canal de fuego, la seta y el tejado, la gran riada de nenúfares y, al final,
// agua, soplido y agua otra vez desde el nenúfar del molinillo.
// Secretos: el sótano del canal de fuego y la cámara del tejado (panzazo: suelo agrietado sin munición cerca),
// la viga de los anzuelos (mordisco) y el nicho de piedra reforzada junto al farol del caz (guindilla).
'use strict';
(() => {
  const { screen, join, G3 } = NIVEL;
  const molino = join(
    // 1 · La orilla: tablas para calentar.
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '..............*.....',
      '.............===....',
      '....................',
      '....................',
      '.........===........',
      '..@..N..,.......s...', ...G3),
    // 2 · Los surcos anegados: rana en el bancal y un mosquito sobre el foso ancho (aleteo).
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '..........*.........',
      '....................',
      '........###.........',
      '......f.###....m....',
      '##~~~#######~~~~~###',
      '##~~~#######~~~~~###',
      '####################'),
    // 3 · La chimenea de raíces (ventosa) hasta el cantil; una hoguera arriba.
    screen(
      '....................',
      '....................',
      '....*.M........F....',
      '......M...##########',
      '......M...M#########',
      '......M...M#########',
      '......M...M#########',
      '......M...M#########',
      '......M...M#########',
      '..........M#########',
      '..........M#########', ...G3),
    // 4 · Abajo del cantil, el farol y el molinillo: la compuerta del caz se cierra enseguida.
    //     El nicho de piedra reforzada (guindilla) y una piedra para cargarla.
    screen(
      '..........##########',
      '..........##########',
      '..........##########',
      '######....##########',
      '######....##########',
      '######....##########',
      '######....##########',
      '######....##########',
      '######..............',
      '##...X..............',
      '##*..XLVr?.F....F.s.', ...G3),
    // 5 · Fin del túnel (compuerta del molinillo) y la esclusa: la placa en alto se pisa con la caja.
    screen(
      '#####...........G...',
      '#####...........G...',
      '#####...........G...',
      '#####......*....G...',
      '#####...........G...',
      '#####...........G...',
      '#####.....PP....G...',
      '#####.....###...G...',
      '....G.....###...G...',
      '....G.....###...G...',
      '....G.?c..###.f.G...',
      '#~~#################',
      '#~~#################',
      '####################'),
    // 6 · Olga y el caz: la diana en la fachada del molino, alta: hay que saltar y escupir la piedra en el aire.
    screen(
      '...........#########',
      '...........#########',
      '...........#########',
      '...........#########',
      '...........#########',
      '...........#########',
      '...........#########',
      '..........T#########',
      '................G...',
      '................G...',
      '.L?Q.rrr........G...',
      '#######~~~~#########',
      '#######~~~~#########',
      '####################'),
    // 7 · Dentro del molino: la charca y la columna de fuego.
    screen(
      '####################',
      '####################',
      '####################',
      '####################',
      '####################',
      '####################',
      '####################',
      '.........F..........',
      '.........F..........',
      '.........F..........',
      '..?......F.....*....',
      '#####~~~############',
      '#####~~~############',
      '####################'),
    // 8 · El primer río: flotar con el chorro.
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '.........*..........',
      '....................',
      '....................',
      '....................',
      '....................',
      'L?..................',
      '####~~~~~~~~~~######',
      '####~~~~~~~~~~######',
      '####################'),
    // 9 · La cortina de fuego: desde el nenúfar se apaga (y se vuelve a beber).
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '.................F..',
      '.................F..',
      '.................F..',
      '.................F..',
      '.......*.........F..',
      '.................F..',
      '###~~~~~~~~w~~~~~###',
      '###~~~~~~~~~~~~~~###',
      '####################'),
    // 10 · El canal de fuego: charquitas y fuegos en un túnel bajo; bajo las losas agrietadas, el sótano (panzazo).
    screen(
      '####################',
      '####################',
      '####################',
      '####################',
      '####################',
      '####################',
      '####################',
      '####################',
      '....................',
      '....................',
      '....FFF.........FFFF',
      '###~####xxx####~####',
      '###~#####*#####~####',
      '####################'),
    // 11 · La seta y el tejado: rebote, aleteo y chorro sobre las zarzas. En el tejado, la cámara agrietada (panzazo).
    screen(
      '....................',
      '....................',
      '....................',
      '.........*...###xxx#',
      '.............###...#',
      '.............###.*.#',
      '.............#######',
      '.............#######',
      '.............#######',
      '.............#######',
      'L............#######',
      '##~~#..^^^^^^#######',
      '##~~#%%#############',
      '####################'),
    // 12 · La gran riada (1): desde el tejado se baja a la orilla; nenúfar a nenúfar.
    screen(
      '....................',
      '....................',
      '..L.................',
      '####................',
      '####................',
      '####................',
      '####................',
      '####................',
      '####................',
      '####................',
      '####................',
      '######~~~~~~~~~w~~~~',
      '######~~~~~~~~~~~~~~',
      '####################'),
    // 13 · La gran riada (2): mosquitos entre nenúfares; en la otra orilla, los anzuelos de la viga (mordisco).
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '*.................O.',
      '....................',
      '....................',
      '..........m.........',
      '...m................',
      '....................',
      '....................',
      '~~~~~w~~~~~~~~######',
      '~~~~~~~~~~~~~~######',
      '####################'),
    // 14 · La viga: una cría arriba, sólo para quien sepa picar anzuelos.
    screen(
      '....................',
      '......*.............',
      '....####............',
      '....................',
      '..O.................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '...........f........', ...G3),
    // 15 · El nenúfar del molinillo: agua al fuego, soplido al molinillo, agua otra vez y a la otra orilla.
    screen(
      '...................G',
      '...................G',
      '...................G',
      '...................G',
      '.............*.....G',
      '.................F.G',
      '.................F.G',
      '.................F.G',
      '.................F.G',
      '.................F.G',
      '.L?..........V...F.G',
      '###~~~~~~~w~~#~~~###',
      '###~~~~~~~~~~~~~~###',
      '####################'),
    // 16 · Ruca y la barca.
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '.....N.....L.E......',
      '############~~~~~~~~',
      '############~~~~~~~~',
      '####################'));
  NIVEL.registrar({ id: 'molino', name: 'El molino anegado', theme: 'storm', music: 'molino', par: 330, rows: molino,
    intro: 'La tormenta obligó a la Garza a pasar la noche en el molino.',
    ruca: ['Huele a pluma mojada: la Garza durmió en el molino. Y esas hogueras... alguien le ha prendido fuego al pantano.',
      'Cada cría que sueltas vuelve nadando a casa. La Garza ha seguido hacia el muelle del pescador.'],
    signs: [
      'Sopla al molinillo con {puff} y corre: la compuerta del caz se cierra enseguida.',
      'La compuerta sólo se abre mientras algo pese en la placa. Sube con la caja en la boca y déjala encima con {down} y {fish}.',
      'Bigotes también escupe en pleno salto: lo que escupe sale a la altura de su boca.',
      'Bigotes ya sorbe agua: mantén {fish} de cara a la charca. Luego escúpela a la hoguera.',
      'El río es ancho. Con agua en la boca, salta y mantén {fish} en el aire: el chorro te sostiene. Con {down} bajas; con {up} remontas un poco.',
      'Con la boca llena no se sopla. Desde el nenúfar: agua al fuego, soplido al molinillo... y a beber otra vez.'],
    maestro: { quien: 'olga', poder: 'chorro',
      dialogo: ['¡Una visita con esta tormenta! Pasa, pasa, que te calas. Soy Olga, la molinera.',
        'Esas hogueras me tienen el molino sitiado, y la riada se ha comido medio camino. Con agua se apagan... si alguien la llevara.'],
      despedida: 'Sorbe agua de la charca y escúpela al fuego. Y si el río es ancho, ¡chorro y a flotar!',
      encargo: { tipo: 'dianas', n: 1,
        pide: 'Pero la riada me ha atascado la compuerta. ¿Ves la diana en la pared del molino, sobre el caz? Dale con una piedra... pero está alta: salta y escupe en el aire.',
        hecho: '¡Clac! Ya corre el agua. Toma, Bigotes: un nenúfar azul. Da una sed... ¡bebe todo el río que quieras!' } },
    secretos: [{ poder: 'panzazo', crias: 2 }, { poder: 'mordisco', crias: 1 }, { poder: 'guindilla', crias: 1 }] });
})();
