// GLUP — nivel 4.
'use strict';
(() => {
  const { screen, join, G3 } = NIVEL;
  // ---------------------------------------------------------------- 4 · El molino anegado
  // Tormenta. Olga da el trago de agua (nenúfar): apagar fuegos fatuos y flotar sobre el río; la placa;
  // la seta y el aleteo suben al tejado. El suelo agrietado queda para el panzazo (secreto).
  const molino = join(
    screen(
      '....................',
      '....................',
      '..@..N.....,........', ...G3),
    screen(
      '....................',
      '....................',
      '..........##########',
      '..........##########',
      '....................',
      '..Q.?.....FFFF....*.',
      '#####~~~############',
      '#####~~~############',
      '####################'),
    screen(
      '....................',
      '....................',
      '######..............',
      '######......*.......',
      '....................',
      '...?................',
      '######~~~~~~~~~~~~~#',
      '######~~~~~~~~~~~~~#',
      '####################'),
    screen(
      '..............G.....',
      '..............G.....',
      '..............G.....',
      '..............G.....',
      '..............G.....',
      '..............G.....',
      '..............G.....',
      '..............G.....',
      '..............G.....',
      '..............G.....',
      '..c...?...PP..G..*..', ...G3),
    screen(
      '...............#####',
      '...............#####',
      '...............#####',
      '...............#####',
      '...............#####',
      '...............#####',
      '...............#####',
      '....#####xxx########',
      '....#...............',
      '...........*........',
      '.L..................', ...G3),
    screen(
      '#####...............',
      '#####...............',
      '#####...............',
      '#####...............',
      '#####.........######',
      '#####....*....######',
      '#####.........######',
      '#####.........######',
      '..............######',
      '..............######',
      '..............######',
      '########...#########',
      '########.%.#########',
      '####################'),
    screen(
      '....................',
      '....................',
      '...............*....',
      '....................',
      '######......###.....',
      '######......###.....',
      '######..............',
      '######..............',
      '######..............',
      '######..............',
      '######....f....FF...',
      '######~~~~##########',
      '######~~~~##########',
      '####################'),
    screen(
      '....................',
      '....................',
      '..........*.........',
      '..............m.....',
      '....................',
      '.L..................',
      '####~~~~~~~w~~~~~~~~',
      '####~~~~~~~~~~~~~~~~',
      '####################'),
    screen(
      '....................',
      '....................',
      '........*...........',
      '....................',
      '....................',
      '....................',
      '~~~~~###############',
      '~~~~~###############',
      '####################'),
    screen(
      '................G...',
      '................G...',
      '................G...',
      '.............*..G...',
      '................G...',
      '................G...',
      '................G...',
      '..........PP....G...',
      '..........##....G...',
      '..........##....G...',
      '..c.?.....##....G...', ...G3),
    screen(
      '....................',
      '.........*..........',
      '....FFF...N...L.E...',
      '#~~###########~~~~~~',
      '#~~###########~~~~~~',
      '####################'));
  NIVEL.registrar({ id: 'molino', name: 'El molino anegado', theme: 'storm', music: 'storm', par: 200, rows: molino,
    intro: 'La tormenta obligó a la Garza a pasar la noche en el molino.',
    ruca: ['Huele a pluma mojada: la Garza durmió aquí. Y esos fuegos fatuos... el pantano está revuelto.',
      'Cada cría que sueltas vuelve nadando a casa. La Garza ha seguido hacia el muelle del pescador.'],
    signs: [
      'Bigotes también sorbe agua: mantén {fish} frente a la charca. Escúpela sobre el fuego fatuo.',
      'El río es ancho. Con agua en la boca, mantén {fish} en el aire: el chorro te sostiene.',
      'La compuerta sólo se abre mientras algo pese en la placa. Deja la caja encima con {down} y {fish}.',
      'Esta placa está en alto: sube con la caja en la boca.'],
    maestro: { quien: 'olga', poder: 'chorro',
      dialogo: ['¡Una visita con esta tormenta! Pasa, pasa, que te calas. Soy Olga, la molinera.',
        'Esos fuegos fatuos me tienen el molino sitiado. Con agua se apagan... si alguien la llevara.',
        'Este nenúfar azul da una sed... Cómetelo, Bigotes, y bebe todo el río que quieras.'],
      despedida: 'Sorbe agua de la charca y escúpela al fuego. Y si el río es ancho, ¡chorro y a flotar!' },
    secretos: [{ poder: 'panzazo', crias: 2 }, { poder: 'mordisco', crias: 1 }] });
})();
