// GLUP — nivel 5 · El muelle del pescador. Al anochecer, tablones, nenúfares, cangrejos y una balsa
// llevan hasta la caseta de Don Anselmo, en lo alto de unos pilotes. Quiere su caja de aparejos (encargo
// «entregar»): hay que subirla en la boca por la chimenea de raíces. A cambio da el anzuelo viejo, y la
// segunda mitad es el caladero: cadenas de anzuelos sobre el agua con mosquitos rondando, saltar y morder
// al vuelo, flotar con el chorro hasta que se acaba y morder el anzuelo de delante, y un pozo de anzuelos.
// Escondidas: una pasarela en el cielo sobre la seta del hoyo (panzazo para rebotar muy alto), una
// bodega bajo la piedra agrietada del pilote del caladero (panzazo), y dos huecos tras piedra reforzada
// (guindilla): bajo la caseta y en el cobertizo.
// Faroles: tras los primeros tablones (antes de los nenúfares), en el islote antes de la balsa, junto a Don
// Anselmo (empieza el caladero), tras el caladero, en el cobertizo y antes de los nenúfares de las ranas. Se
// quitaron el de antes del río (a trece pasos del islote) y el de al lado de la barca.
'use strict';
(() => {
  const { screen, join, G3 } = NIVEL;
  const muelle = join(
    // 1 · La orilla: el primer tablón en alto pide el aleteo.
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '...........*........',
      '....................',
      '..........====......',
      '....................',
      '....................',
      '..@..N.......s...?..', ...G3),
    // 2 · El primer embarcadero: dos tramos de tablones y una rana.
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '.............*......',
      '....................',
      '...............f....',
      '...=====....======..',
      '....................',
      '##~~~~~~~~~~~~~~~~~#',
      '##~~~~~~~~~~~~~~~~~#',
      '####################'),
    // 3 · Nenúfares, con un mosquito encima.
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '...........*........',
      '....................',
      '........m...........',
      '....................',
      '.L..................',
      '####w~~w~~w~~w~~####',
      '####~~~~~~~~~~~~####',
      '####################'),
    // 4 · El cangrejo, la seta del hoyo (y la pasarela del cielo) y el río que se cruza flotando.
    screen(
      '................*...',
      '....=============...',
      '....................',
      '....................',
      '....................',
      '..................*.',
      '....................',
      '....................',
      '....................',
      '....................',
      '.r...K....?.........',
      '##..##########~~~~~~',
      '##..##########~~~~~~',
      '##%%################'),
    // 5 · El islote del farol y la balsa: soplando hacia atrás se cruza el remanso.
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '..............*.....',
      '..........m.........',
      '....................',
      '....................',
      '.....L..R...........',
      '~~~~~###~~~~~~~~~~~~',
      '~~~~~###~~~~~~~~~~~~',
      '####################'),
    // 6 · La caseta de Don Anselmo, en lo alto; la caja al pie de la chimenea de raíces.
    screen(
      '....................',
      '....................',
      '.............Q.L.?..',
      '......M..M##########',
      '......M..M##########',
      '......M..M##########',
      '......M..M##########',
      '......M..M##########',
      '......M..M##########',
      '.........X.*########',
      '....cc...X..########',
      '~~~~################',
      '~~~~################',
      '####################'),
    // 7 · El caladero: anzuelos, el pilote de piedra agrietada y morder al vuelo.
    screen(
      '....................',
      '....................',
      '....................',
      '..O....O........O...',
      '....................',
      '...................m',
      '.........#xxx#......',
      '.........#...#......',
      '.........#.*.#......',
      '.........#...#......',
      '.........#####......',
      '~~~~~~~~~#####~~~~~~',
      '~~~~~~~~~#####~~~~~~',
      '####################'),
    // 8 · Tierra otra vez: tablones, un cangrejo y el farol.
    screen(
      '....................',
      '....................',
      '....................',
      '.O....O.............',
      '............*.......',
      '....................',
      '.........======.....',
      '....................',
      '....................',
      '....................',
      '..........r..K..L...',
      '~~~~~~~~~###########',
      '~~~~~~~~~###########',
      '####################'),
    // 9 · Flotar con el chorro hasta que se acaba... y morder el anzuelo de delante.
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '...........*........',
      '...................O',
      '....................',
      '....................',
      '.?..................',
      '###~~~~~~~~~~~~~~~~~',
      '###~~~~~~~~~~~~~~~~~',
      '####################'),
    // 10 · El cobertizo (con su hueco tras piedra reforzada).
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....O...........####',
      '................X..#',
      '................X..#',
      '.......r....s...X*.#',
      '~~~~~~~#############',
      '~~~~~~~#############',
      '####################'),
    // 11 · El pozo de los anzuelos: de uno a otro hasta arriba.
    screen(
      '....................',
      '................L...',
      '.........O..########',
      '............########',
      '............########',
      '....O.......########',
      '............########',
      '............########',
      '.........O..########',
      '............########',
      '............########',
      '####~~~~~~~~########',
      '####~~~~~~~~########',
      '####################'),
    // 12 · La última cadena: anzuelos lejos y a distinta altura, con mosquitos.
    screen(
      '..........*.........',
      '....................',
      '...O....O...........',
      '....................',
      '................O...',
      '....................',
      '....................',
      '.............m......',
      '....................',
      '....................',
      '....................',
      '~~~~~~~~~~~~~~~~~~~~',
      '~~~~~~~~~~~~~~~~~~~~',
      '####################'),
    // 13 · El final de la cadena y tierra firme.
    screen(
      '....................',
      '....................',
      '....................',
      '......O.............',
      '.O..................',
      '....................',
      '....m...............',
      '....................',
      '....................',
      '....................',
      '............L.......',
      '~~~~~~~~~~##########',
      '~~~~~~~~~~##########',
      '####################'),
    // 14 · Nenúfares con ranas.
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '..........*.........',
      '....................',
      '....................',
      '....................',
      '........f.......f...',
      '##~~w~~~w~~~w~~~w~##',
      '##~~~~~~~~~~~~~~~~##',
      '####################'),
    // 15 · La barca.
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '....................',
      '..N.........E.......',
      '###########~~~~~~~~~',
      '###########~~~~~~~~~',
      '####################'));
  NIVEL.registrar({ id: 'muelle', name: 'El muelle del pescador', theme: 'dusk', music: 'muelle', par: 260, rows: muelle,
    intro: 'En el muelle viejo, un pescador vio pasar a la Garza.',
    ruca: ['Don Anselmo lleva toda la vida pescando en este muelle. Si alguien sabe de anzuelos, es él. Vive en la caseta de los pilotes.',
      'La Garza cruzó la turbera hacia el cerro. Ojo allí: el suelo es blando y engaña.'],
    signs: [
      'Muelle viejo. Los tablones aguantan; el agua, no. Si uno está muy alto, salta y, en el aire, salta otra vez.',
      'Cangrejo: una pedrada lo voltea. Y el río es ancho: sorbe agua con {fish} y, en el aire, mantén {fish} para flotar.',
      'Frente a un anzuelo, mantén {fish}: Bigotes pica y el sedal os sube. Colgada, sigue con {fish} mirando al siguiente. Si está lejos, salta, aletea y muerde al vuelo.',
      'Con agua en la boca, salta y mantén {fish}. Cuando se acabe el chorro no sueltes: Bigotes morderá el anzuelo que tenga delante.'],
    maestro: { quien: 'anselmo', poder: 'mordisco', bocado: 'un anzuelo viejo',
      dialogo: ['Buenas tardes, pequeña. ¿Una garza grande? La vi pasar esta mañana, con el buche lleno.',
        'Así que ese pez gato tuyo quiere morder anzuelos... Los peces listos muerden el cebo y no el hierro. Bueno, ya veremos.'],
      despedida: 'Frente al anzuelo, mantén {fish}: el pez pica y el sedal os sube. Colgada, mira al siguiente. ¡Buena pesca!',
      encargo: { tipo: 'entregar', cosa: 'crate', radio: 48,
        pide: 'Pero antes, ¿me subes la caja de aparejos? Se me cayó al pie de los pilotes. Por la chimenea de raíces se sube, si llevas la caja en la boca. Déjala a mis pies con {down} y {fish}.',
        hecho: '¡Mi caja! Aquí guardo el mejor anzuelo del pantano. Es tuyo, Bigotes. Ahí delante, el caladero: anzuelos hasta la otra orilla.' } },
    secretos: [{ poder: 'panzazo', crias: 2 }, { poder: 'guindilla', crias: 2 }] });
})();
