// GLUP — nivel 6 · La turbera (PROVISIONAL: un esbozo corto que se puede terminar; se rediseñará).
// Canto, el topo, pide que se enciendan los dos faroles (encargo «faroles») y da el canto de río:
// el panzazo rompe la costra agrietada y abre el paso por debajo del muro.
'use strict';
(() => {
  const { screen, join } = NIVEL;
  const turbera = join(
    screen(
      '....................',
      '....................',
      '....................',
      '....................',
      '..............*.....',
      '....................',
      '..@..N....L.........',
      '####################',
      '####################',
      '####################',
      '####################',
      '####################',
      '####################',
      '####################'),
    screen(
      '....................',
      '....................',
      '....................',
      '.........*..........',
      '....................',
      '....................',
      '...Q..........L.....',
      '####################',
      '####################',
      '####################',
      '####################',
      '####################',
      '####################',
      '####################'),
    screen(
      '............########',
      '............########',
      '............########',
      '............########',
      '............########',
      '............########',
      '............########',
      '#####xxx############',
      '#####...############',
      '#####...............',
      '#####...............',
      '#####.*.............',
      '####################',
      '####################'),
    screen(
      '####................',
      '####................',
      '####................',
      '####................',
      '####................',
      '####................',
      '####................',
      '####................',
      '####................',
      '....................',
      '....................',
      '.........*.....E....',
      '##############~~~~~~',
      '##############~~~~~~'));
  NIVEL.registrar({ id: 'turbera', name: 'La turbera', theme: 'storm', music: 'storm', par: 90, rows: turbera,
    intro: 'La turbera es blanda por fuera y dura por dentro.',
    ruca: ['Bajo la turbera hay galerías. El topo Canto las conoce todas... pero ve fatal a oscuras.'],
    signs: [],
    maestro: { quien: 'canto', poder: 'panzazo',
      dialogo: ['¿Quién va? ¿Eres una raíz? ¿Una rana? Ah, una niña. Perdona, sin luz no veo tres en un burro.'],
      despedida: 'En el aire, {down} y {jump}: ¡panzazo! La costra agrietada se rompe y vas para abajo.',
      encargo: { tipo: 'faroles', n: 2,
        pide: 'Enciende los dos faroles de la turbera, anda, que así no hay quien cave. Luego te enseño a romper el suelo.',
        hecho: '¡Ahora sí veo! Toma, un canto de río. Déjate caer con todo tu peso, como una piedra.' } },
    secretos: [{ poder: 'guindilla', crias: 1 }] });
})();
