// GLUP — nivel 7.
'use strict';
(() => {
  const { screen, join, G3 } = NIVEL;
  // ---------------------------------------------------------------- 7 · La cueva de barro
  // A oscuras. Don Pinzas da el escupitajo picante (guindilla) si le apagas el fogón: rompe piedra reforzada y atraviesa cangrejos.
  // El túnel del molinillo se cruza corriendo.
  const cueva = join(
    screen(
      '.................X..',
      '.................X..',
      '.................X..',
      '.................X..',
      '........*........X..',
      '.................X..',
      '.................X..',
      '.................X..',
      '.................X..',
      '.................X..',
      '..@...Q..F.r...N.X..',
      '#############~~#####', '####################', '####################'),
    screen(
      '....................',
      '..........*.........',
      '....................',
      '....................',
      '....................',
      '...%....^^^^^....%..', ...G3),
    screen(
      '...........*........',
      '....................',
      '....................',
      '..?.....FFFF........',
      '###~~###############',
      '###~~###############',
      '####################'),
    screen(
      '....................',
      '....................',
      '....................',
      '.....###############',
      '.....###############',
      '.....###############',
      '....................',
      '.?..V...............', ...G3),
    screen(
      '....................',
      '....................',
      '....................',
      '#############.......',
      '#############.......',
      '#############.......',
      '....................',
      '..........G.....*...', ...G3),
    screen(
      '....................',
      '............########',
      '.........O..########',
      '......*.....########',
      '............########',
      '..........O.########',
      '............########',
      '............########',
      '.........O..########',
      '............########',
      '..?.........########', ...G3),
    screen(
      '..................G.',
      '########..........G.',
      '########..........G.',
      '########..*.......G.',
      '########..........G.',
      '########..........G.',
      '########..........G.',
      '########..........G.',
      '########..........G.',
      '########..........G.',
      '########.rK.K.K..TG.', ...G3),
    screen(
      '.............X......',
      '.............X......',
      '.............X......',
      '.............X......',
      '.............X......',
      '.............X......',
      '.............X......',
      '.............X......',
      '....######...X......',
      '....######...X...*..',
      '..r.......s..X...H..', ...G3),
    screen(
      '....................',
      '.......*............',
      '..L.N........E......',
      '##########~~~~~~~~~~',
      '##########~~~~~~~~~~',
      '####################'));
  NIVEL.registrar({ id: 'cueva', name: 'La cueva de barro', theme: 'cave', music: 'cave', par: 170, rows: cueva,
    intro: 'Bajo el cerro, un río oscuro lleva hasta el nido.',
    ruca: ['Esa pared no la rompe una pedrada normal. Hace falta algo... picante.',
      'El río de la cueva sigue bajo tierra. Ve con cuidado, Nila.'],
    signs: [
      'Esa charca da para apagar el fuego. O salta con ganas.',
      'Sopla al molinillo con {puff} y corre: el túnel es largo.',
      'Anzuelos hacia arriba: sorbe con {up}, Bigotes pica y el sedal os sube; desde cada uno, busca el siguiente.'],
    maestro: { quien: 'pinzas', poder: 'guindilla',
      dialogo: ['¡Clac, clac! ¿Visitas en mi cocina? Soy Don Pinzas, cocinero de la cueva.',
        'Mi guiso lleva guindilla del pantano. Pica tanto que se te sale el fuego por la boca.'],
      despedida: 'Con la boca llena, mantén {fish} hasta que Bigotes se ponga rojo, y suelta. ¡Ni la piedra aguanta!',
      encargo: { tipo: 'apagar', radio: 4,
        pide: '¡Pero el fogón se me ha desmandado! Apágamelo con agua y te doy una guindilla. Hay una charca ahí al lado.',
        hecho: '¡Uf, a tiempo! El guiso está salvado. Toma, Bigotes: una guindilla del pantano, de las buenas.' } },
    secretos: [{ poder: 'resbalon', crias: 1 }] });
})();
